- name: Replace Docker
  hosts: test1
  become: yes

  tasks:
  - name: Pull image
    shell: "docker pull anpod07/nginx-test:latest"
  - name: Replace image
    shell:
      cmd: "
            if [ -n \"`docker ps -a | grep myapp`\" ];
             then 
              docker stop myapp;
              docker rmi myapp:latest;
            fi
           "
  - name: Tag image
    shell: "docker tag anpod07/nginx-test:latest myapp:latest"
  - name: Run new tagged image
    shell: "docker run -d --rm --name myapp -p 80:80 myapp:latest"
  - name: Remove pulled image
    shell: "docker rmi anpod07/nginx-test:latest"

  - name: Check Docker service is running
    shell: "systemctl status docker.service"
    changed_when: false
    register: out1
  - debug: msg="{{out1.stdout_lines}}"
  - name: Check docker images
    shell: "docker images"
    changed_when: false
    register: out2
  - debug: msg="{{out2.stdout_lines}}"
  - name: Check docker ps
    shell: "docker ps"
    changed_when: false
    register: out3
  - debug: msg="{{out3.stdout_lines}}"

